apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
    route:
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 30m
      receiver: "telegram"
      routes:
        - receiver: "telegram"
          group_wait: 10s
          match_re:
            severity: critical|warning
          continue: true
    receivers:
     - name: "telegram"
       telegram_configs:
         - send_resolved: true
           bot_token: '5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs'
           chat_id: -1001763459775
           message: "{{ range .Alerts }}\n Namespace: {{ .Annotations.namespace }}\n Summary: {{ .Annotations.summary }}\n Description: {{ .Annotations.description }}\n {{ end }}"
           parse_mode: ''
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: std-017-006
    meta.helm.sh/release-namespace: std-017-006
  creationTimestamp: "2023-09-15T07:41:26Z"
  labels:
    app: alertmanager
    app.kubernetes.io/managed-by: Helm
  name: alertmanager
  namespace: std-017-006
  resourceVersion: "1044729910"
  uid: 34115758-1742-4a04-9f64-b7ef8411a151
