stages:
  - module-pipelines

kubernetes:
  stage: module-pipelines
  trigger:
    include:
      - "/kubernetes/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
     - kubernetes/**/*

sausage-store-chart:
  stage: module-pipelines
  trigger:
    include:
      - "/sausage-store-chart/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
     - sausage-store-chart/**/*
