stages:
  - deploy

deploy:
  stage: deploy
  image: 
    name: alpine/helm:latest
  script:
    - helm package sausage-store-chart
    - curl -u ${NEXUS_USER}:${NEXUS_PASS} ${NEXUS_REPO} --upload-file sausage-store-*.tgz 
