stages:
  - deploy

deploy:
  stage: deploy
  image: 
    name: alpine/helm:latest
    entrypoint: ['']
  script:
    - helm package sausage-store-chart
    - curl -u ${NEXUS_HELM_USER}:${NEXUS_HELM_PASS} ${NEXUS_HELM_REPO} --upload-file sausage-store-*.tgz 
