stages:
  - deploy

deploy:
  stage: deploy
  image: 
    name: alpine/helm:latest
    entrypoint: ['']
  script:
    - helm package sausage-store-chart
    - curl -u ${NEXUS_HELM_USER}:${NEXUS_HELM_PASS} --upload-file sausage-store-*.tgz ${NEXUS_HELM_REPO} 
