backend:
  replicaCount: 3
  image:
    repository: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-backend
    imagePullPolicy: Always
    tag: latest
  rollingUpdate:
    maxUnavailable: 2
    maxSurge: 20%
  containerPort: 8090
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 2
    failureThreshold: 6
