global:
  revisionHistoryLimit: 15
  proxyPassHost: backend
  proxyPassPort: 8090
  dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4Tnkwd01EWTZhMHBRTjNBME1XYz0iCgkJfQoJfQp9
  environment: production

backend:
  replicas: 3
  strategy:
    type: RollingUpdate
  image:
    repository: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-backend
    pullPolicy: Always
    tag: latest
  rollingUpdate:
    maxUnavailable: 2
    maxSurge: 20%
  containerPort: 8090
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 2
    failureThreshold: 6 
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerName: "*"
    minAllowed:
      cpu: 0m
      memory: 0Mi
    maxAllowed:
      cpu: 1
      memory: 500Mi
  pg:
    url: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi0zY3N4bTF3cTQwaGRlbXdxLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDE3LTAwNg==
    username: c3RkLTAxNy0wMDY=
    password: VGVzdHVzcjEyMzQ=

backend-report:
  replicas: 1
  strategy:
    type: Recreate
  image:
    repository: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-backend-report
    pullPolicy: Always
    tag: latest
    requests:
      cpu: "100m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"
  containerPort: 8080
  minReplicas: 1
  maxReplicas: 5
  resource:
    cpu:
      utilization:
        averageUtilization: 75
  db: bW9uZ29kYjovL3N0ZC0wMTctMDA2OlRlc3R1c3IxMjM0QHJjMWMtYmlmeDdiYmUzZGQ5Y2k2MC5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE4L3N0ZC0wMTctMDA2P3Rscz10cnVlJnRsc0FsbG93SW52YWxpZENlcnRpZmljYXRlcz10cnVl

frontend:
  replicas: 1
  strategy:
    type: Recreate
  image:
    repository: gitlab.praktikum-services.ru:5050/std-017-006/sausage-nginx/sausage-nginx
    pullPolicy: Always
    tag: latest
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  containerPort: 8080
  ingress:
    tls:
      hosts: std-017-006.k8s.praktikum-services.tech
    rules:
      host: std-017-006.k8s.praktikum-services.tech
      port: 8080
