---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.image.requests.cpu }}
            memory: {{ .Values.image.requests.memory }}
          limits:
            cpu: {{ .Values.image.limits.cpu }}
            memory: {{ .Values.image.limits.memory }}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        ports:
        - name: frontend
          containerPort: {{ .Values.containerPort }}
      imagePullSecrets:
      - name: docker-config-secret
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:  
              matchExpressions:
              - key: application
                operator: In
                values:
                - front

