# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: pg 
  labels:
    app: pg
data:
  url: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi0zY3N4bTF3cTQwaGRlbXdxLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDE3LTAwNg==
  username: c3RkLTAxNy0wMDY=
  password: VGVzdHVzcjEyMzQ= 
#metadata:
#  name: vault
#  labels:
#    app: vault
#data:
#  vault_token: aHZzLmNadVFhTDBiMVRNOE5qSGtVWHY4V2xQcw==
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4Tnkwd01EWTZhMHBRTjNBME1XYz0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
