---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion}}"
    helm.sh/chart: "{{ Chart.Name}}-{{ .Chart.Version}}"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.global.environment }}"
spec:
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
      - name: backend-report
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.image.requests.cpu }}
            memory: {{ .Values.image.requests.memory }}
          limits:
            cpu: {{ .Values.image.limits.cpu }}
            memory: {{ .Values.image.limits.memory }}
        ports:
        - name: backend-report
          containerPort: {{ .Values.containerPort }}
        env:
        - name: DB
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: db
      imagePullSecrets:
      - name: docker-config-secret        

