# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app: mongodb
data:
  db: {{ .Values.db }}
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: {{ .Values.global.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson

