---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
      maxSurge: {{ .Values.maxSurge }}
  selector:
    matchLabels:    
      app: backend
  template:
    metadata:
      labels:
        app: backend
    # шаблон для создания Pod'ов
    spec:
      containers:
      - name: backend
        image: gitlab.praktikum-services.ru:5050/std-017-006/sausage-store/sausage-backend:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: pg
              key: url 
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: pg
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg
              key: password
        ports:
        - name: backend
          containerPort: {{ .Values.containerPort }}
        livenessProbe:
          # проверка живучести выполнит запрос HTTP GET       
          httpGet:
            # путь к запросу в HTTP-запросе          
            path: /actuator/health
            port: {{ .Values.containerPort }}
          # перед исполнением первой проверки подождать 15 секунд, пока стартанёт бэкенд          
          initialDelaySeconds: {{ .Values.initialDelaySeconds }}
          # период выполнения проверки
          periodSeconds: {{ .Values.periodSeconds }}
          # максимальное время выполнения проверки (по умолчанию 1 раз)
          timeoutSeconds: {{ .Values.timeoutSeconds }}
          # сколько раз пробовать попытку, если она провалилась (по умолчанию 1 раз)
          failureThreshold: {{ .Values.failureThreshold }}
      # чтобы Кубер мог скачивать образы из нашего GitLab Registry  
      imagePullSecrets:
      - name: docker-config-secret
