---
apiVersion: v1
kind: Secret
metadata:
  name: pg 
  labels:
    app: pg
data:
  url: {{ .Values.pg.url }}
  username: {{ .Values.pg.username }}
  password: {{ .Values.pg.password }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: {{ .Values.global.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson

