---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.proxyPassHost }}
  labels:
    app: backend 
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.global.proxyPassPort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: backend

