---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Release.Name }}
  updatePolicy:
    updateMode: {{ .Values.updatePolicy.updateMode }}
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        cpu: {{ .Values.resourcePolicy.minAllowed.cpu }}
        memory: {{ .Values.resourcePolicy.minAllowed.memory }}
      maxAllowed:
        cpu: {{ .Values.resourcePolicy.maxAllowed.cpu }}
        memory: {{ .Values.resourcePolicy.maxAllowed.memory }}
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

