stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  environment:
    name: kubernetes
    url: https://std-017-006.k8s.praktikum-services.tech
  before_script:
    - mkdir -p ${HOME}/.kube
    - touch ${HOME}/.kube/config
    - echo ${KUBE_CONFIG} > ${HOME}/.kube/config
    - chmod 664 ${HOME}/.kube/config
    - KUBECONFIG=${HOME}/.kube/config
    - export KUBECONFIG  
  script:
    - cat ${HOME}/.kube/config
    - kubectl apply -f kubernetes/backend --kubeconfig="${HOME}/.kube/config"
    #- kubectl apply -f kubernetes/backend-report
    #- kubectl apply -f kubernetes/frontend
    - rm -f ~/.kube/config
