stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  environment:
    name: kubernetes
    url: https://std-017-006.k8s.praktikum-services.tech
  before_script:
    - mkdir -p ~/.kube
    - echo ${KUBE_CONFIG} >> ~/.kube/config
    - KUBECONFIG=~/.kube/config
    - export KUBECONFIG  
  script:
    - cat ~/.kube/config
    - cd kubernetes
    - ls /root/.kube
    - kubectl apply -f backend 
    #- kubectl apply -f kubernetes/backend-report
    #- kubectl apply -f kubernetes/frontend
    - rm -f ~/.kube/config
