stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  environment:
    name: kubernetes
    url: https://std-017-006.k8s.praktikum-services.tech
  before_script:
    - mkdir -p ~/.kube
    - cat ${KUBE_CONFIG} > ~/.kube/config
  script:
    - kubectl apply -f kubernetes/backend
    #- kubectl apply -f kubernetes/backend-report
    #- kubectl apply -f kubernetes/frontend
    - rm -f ~/.kube/config
