stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  environment:
    name: kubernetes
    url: https://std-017-006.k8s.praktikum-services.tech
  before_script:
    - mkdir -p ~/.kube
    - chmod 700 ~/.kube
    - cat ${KUBE_CONFIG} > ~/.kube/config
    - chmod 644 ~/.kube/config
    - KUBECONFIG=~/.kube/config
    - export KUBECONFIG
    - echo -----------------------
    - cat ~/.kube/config
    - echo ----------------------- 
  script:
    - kubectl apply -f kubernetes/backend
    - kubectl apply -f kubernetes/backend-report
    - kubectl apply -f kubernetes/frontend
    - rm -f ~/.kube/config
