# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app: mongodb
data:
  db: bW9uZ29kYjovL3N0ZC0wMTctMDA2OlRlc3R1c3IxMjM0QHJjMWEtdTBud3AwNmdid2g4cXNvcS5tZGIueWFuZGV4Y2xvdWQubmV0OjI3MDE4L3N0ZC0wMTctMDA2P3Rscz10cnVlJnRsc0FsbG93SW52YWxpZENlcnRpZmljYXRlcz10cnVl
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4Tnkwd01EWTZhMHBRTjNBME1XYz0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
